name: Deploy React to TurboCloud FTP

on:
  push:
    branches:
      - main # Mude para master se o nome da sua branch principal for master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegar o código fonte mais recente
        uses: actions/checkout@v4

      - name: ⚙️ Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🏗️ Gerar o Build de Produção
        run: npm run build

      - name: 🚀 Sincronizar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: /public_html/
          security-option: loose
          dangerous-clean-slate: false