name: Deploy React to TurboCloud FTP

on:
  push:
    branches:
      - main # Executa a automação toda vez que você fizer push na branch main (altere se sua branch principal for 'master')

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Pegar o código fonte mais recente
        uses: actions/checkout@v4

      - name: ⚙️ Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🏗️ Gerar o Build de Produção
        run: npm run build

      - name: 🚀 Sincronizar arquivos via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # Se seu projeto usa Create React App altere para ./build/
          server-dir: /public_html/
          dangerous-clean-slate: false # Impede que arquivos fora da pasta do React (como pastas de e-mail) sejam apagados